Add tests for useAbsolutePositioning hook
steroids/react pull request #200
Opened 2023-09-12 10:09 UTC by fogarea

2023-09-13 10:35 UTC, Daria-Kuzminykh commented on tests/hooks/useAbsolutePositioning.test.tsx
> +    it('should change position from top to the bottom correctly', () => {
Странно, что в блоке выше проверяет корректную позицию top
Этот блок проверяет корректную смену позиции top на bottom.
При этом функция calculateAbsolutePosition в обоих блоках принимает одинаковые аргументы. При одинаковых аргументах должен получаться одинаковый результат. Получается, что мы в обоих случаях проверили, что позиция top поменяется на bottom, так?

2023-09-13 10:35 UTC, Daria-Kuzminykh commented on tests/hooks/useAbsolutePositioning.test.tsx
> +const enum POSITIONS {
Positions

2023-09-13 10:35 UTC, Daria-Kuzminykh commented on tests/hooks/useAbsolutePositioning.test.tsx
> +    top = 'top',
TOP, BOTTOM и т. д.

2023-09-13 10:35 UTC, Daria-Kuzminykh commented on tests/hooks/useAbsolutePositioning.test.tsx
> +    bottom= 'bottom',
Перед = должен быть пробел

2023-09-13 10:35 UTC, Daria-Kuzminykh commented on tests/hooks/useAbsolutePositioning.test.tsx
> +const enum POSITIONS {
Предлагаю и в самом хуке сделать не type Positions, а enum. Чтобы во всех таких случаях:

<img width="223" alt="image" src="https://github.com/steroids/react/assets/75027465/c0feda6c-7d3d-4192-8c84-7164b3fdd775">

Использовать константы, а не строки.

Тогда в этот тест можно будет импортировать enum из хука и использовать его

2023-09-14 04:16 UTC, fogarea commented on tests/hooks/useAbsolutePositioning.test.tsx
> +    bottom= 'bottom',
> Перед = должен быть пробел

Done

2023-09-14 04:16 UTC, fogarea commented on tests/hooks/useAbsolutePositioning.test.tsx
> +    top = 'top',
Done

2023-09-14 04:16 UTC, fogarea commented on tests/hooks/useAbsolutePositioning.test.tsx
> +const enum POSITIONS {
Done

2023-09-14 04:17 UTC, fogarea commented on tests/hooks/useAbsolutePositioning.test.tsx
> +    it('should change position from top to the bottom correctly', () => {
В блоке выше проверяем что значение top для стилей посчиталось корректно (в любом положении позиционирование элемента рассчитывается с помощью top).

А в этом блоке проверяем сменилась ли позиция top на bottom, чтобы потом подставить эту строку в стилях.

То есть да, на выходе в обоих кейсах одинаковый результат, но проверяем разные поля объекта, который возвращает хук.

Но вообще да, можно запутаться. Назову кейсы более понятно)

2023-09-20 06:13 UTC, RaayNoff requested changes

2023-09-20 06:13 UTC, RaayNoff commented on tests/hooks/useAbsolutePositioning.test.tsx
> +            expect(result.current.isComponentVisible).toEqual(true);
`toEqual `и `toBe` у нас в тестах должны принимать в себя константы, объявленные либо в скопе `describe` функции, либо в скопе конкретного test suite. Поэтому для этого конкретного true нужно объявить константу `const EXCPECTED_COMPONENT_VISIBLE = true `. Все тесты ниже тоже должны ожидать результат в константах.

2023-09-20 06:13 UTC, RaayNoff commented on tests/utils/calculateComponentAbsolutePosition.test.ts
> +import {Positions} from '../../src/hooks/useAbsolutePositioning';
В этом файле все ок, константы для таких тест кейсов не вижу смысла объявлять, только лишняя нагрузка на глаза и ухудшение читаемости.

2023-09-20 07:23 UTC, fogarea commented on src/hooks/useAbsolutePositioning.tsx
> +export const enum Positions {
Done

2023-09-20 07:23 UTC, fogarea commented on src/hooks/useAbsolutePositioning.tsx
> +export type Position = (typeof Positions)[keyof typeof Positions] | string;
Done

2023-09-20 07:32 UTC, fogarea commented on src/hooks/useAbsolutePositioning.tsx
> +    const useAutoPositioning = props.autoPositioning ?? true;
Done

2023-09-20 07:37 UTC, fogarea commented on src/ui/layout/Tooltip/Tooltip.tsx
> +    position?: Positions,
Done

2023-09-20 07:39 UTC, fogarea commented on src/hooks/useAbsolutePositioning.tsx
> +     * Показывать ли подсказку сразу после рендера страницы
Done

2023-09-20 07:39 UTC, fogarea commented on src/hooks/useAbsolutePositioning.tsx
>      }, [props.gap]);
Done

2023-09-20 07:39 UTC, fogarea commented on src/ui/layout/Tooltip/Tooltip.tsx
> +    position: Positions,
Done

2023-09-20 08:07 UTC, RaayNoff commented on tests/hooks/useAbsolutePositioning.test.tsx
> +            expect(result.current.isComponentVisible).toEqual(true);
Забыл упомянуть, константа должна быть в camelCase'e, ошибся немного так что  `const expectedComponentVisible = true`

2023-09-20 08:49 UTC, fogarea commented on tests/hooks/useAbsolutePositioning.test.tsx
> +            expect(result.current.isComponentVisible).toEqual(true);
Done

2023-09-20 08:49 UTC, fogarea commented on src/ui/layout/Tooltip/Tooltip.tsx
> +        ...props,
Done

2023-09-20 09:01 UTC, fogarea commented on src/hooks/useAbsolutePositioning.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
Done

2023-09-21 05:17 UTC, RaayNoff approved these changes

2023-09-26 05:02 UTC, merged