Steroids/dev#163
steroids/react pull request #203
Opened 2023-09-19 05:29 UTC by fogarea

2023-09-20 08:26 UTC, RaayNoff requested changes

2023-09-20 08:26 UTC, RaayNoff commented on tests/hooks/useLayout.test.tsx
> +import configureMockStore from 'redux-mock-store';
import '@testing-library/jest-dom';
забыл, чтобы jest, it, describe не подчеркивались как ошибка

2023-09-20 08:26 UTC, RaayNoff commented on tests/hooks/useLayout.test.tsx
> +import * as authActions from '../../src/actions/auth';
Добавь константы, по аналогии с useAbsolutePositioning.test.tsx

2023-09-20 09:41 UTC, fogarea commented on tests/hooks/useLayout.test.tsx
> +import * as authActions from '../../src/actions/auth';
Done

2023-09-20 09:41 UTC, fogarea commented on tests/hooks/useLayout.test.tsx
> +import configureMockStore from 'redux-mock-store';
Done

2023-09-20 09:45 UTC, fogarea commented on tests/renderHookWithStore.tsx
> +export default function renderHookWithStore<
Done

2023-09-21 05:15 UTC, RaayNoff approved these changes

2023-09-21 05:15 UTC, merged