Add tests for useAddressBar hook
steroids/react pull request #215
Opened 2023-09-27 04:07 UTC by fogarea

2023-09-27 06:18 UTC, RaayNoff requested changes

2023-09-27 06:18 UTC, RaayNoff commented on tests/hooks/useAddressBar.test.tsx
> +import configureMockStore from 'redux-mock-store';
Импорт jest

2023-09-27 06:18 UTC, RaayNoff commented on tests/hooks/useAddressBar.test.tsx
> +            const convertedValue = defaultFromStringConverter(value, type, null);
null в константу

2023-09-27 06:18 UTC, RaayNoff commented on tests/hooks/useAddressBar.test.tsx
> +            const convertedValue = defaultToStringConverter(value, type, null);
Тоже самое

2023-09-27 06:18 UTC, RaayNoff commented on tests/hooks/useAddressBar.test.tsx
> +const withoutHash = false;
В константы в начало файла, с нэймингом через underscore

2023-09-27 06:18 UTC, RaayNoff commented on tests/hooks/useAddressBar.test.tsx
> +        const {result, rerender} = renderHook(() => useAddressBar(configWithDisabledProp), {
rerender убрать, он не используется

2023-09-27 09:04 UTC, fogarea commented on tests/hooks/useAddressBar.test.tsx
> +import configureMockStore from 'redux-mock-store';
Done

2023-09-27 09:05 UTC, fogarea commented on tests/hooks/useAddressBar.test.tsx
> +            const convertedValue = defaultFromStringConverter(value, type, null);
Done

2023-09-27 09:06 UTC, fogarea commented on tests/hooks/useAddressBar.test.tsx
> +            const convertedValue = defaultToStringConverter(value, type, null);
Done

2023-09-27 09:08 UTC, fogarea commented on tests/hooks/useAddressBar.test.tsx
> +const withoutHash = false;
Done

2023-09-27 09:08 UTC, fogarea commented on tests/hooks/useAddressBar.test.tsx
> +        const {result, rerender} = renderHook(() => useAddressBar(configWithDisabledProp), {
Done

2023-09-28 07:04 UTC, RaayNoff approved these changes

2023-09-29 03:46 UTC, merged