steroids/dev#140
steroids/react pull request #297
Opened 2023-12-20 05:10 UTC by NicolaAK

2023-12-25 07:05 UTC, fogarea requested changes

2023-12-25 08:26 UTC, NicolaAK commented on src/ui/content/Card/Card.tsx
> +import {useMemo} from 'react';
done

2023-12-25 08:28 UTC, NicolaAK commented on src/ui/content/Icon/Icon.tsx
> +    if (!_isString(name)) {
viewProps должны быть перед условием, и icon должен быть выше useMemo

2023-12-25 08:29 UTC, NicolaAK commented on src/ui/content/Avatar/Avatar.tsx
> +    const viewProps = useMemo(() => ({
использует во view только children

2023-12-25 08:36 UTC, NicolaAK commented on src/ui/content/Accordion/AccordionItem.tsx
> +function AccordionItem(props: IAccordionItemViewProps) {
done

2023-12-25 08:36 UTC, NicolaAK commented on src/ui/content/Card/Card.tsx
> +    }), [props.className, props.style]);
done

2023-12-25 08:38 UTC, NicolaAK commented on src/ui/content/CopyToClipboard/CopyToClipboard.tsx
> +import React, {useCallback, useMemo, useRef, useState} from 'react';
done

2023-12-25 08:38 UTC, NicolaAK commented on src/ui/content/Dashboard/Dashboard.tsx
> +        ...props,
done

2023-12-27 05:55 UTC, fogarea approved these changes

2023-12-29 03:40 UTC, merged