Steroids/dev#140 form 1 Передавать из core во view компонентов только необходимые пропсы
steroids/react pull request #304
Opened 2023-12-25 11:09 UTC by NicolaAK

2023-12-28 22:48 UTC, fogarea requested changes

2023-12-28 22:48 UTC, fogarea commented on src/ui/form/DateField/DateField.tsx
> +    const viewProps = useMemo(() => ({
в интерфейсе нужно добавить `import React`, тк проп `maskInputRef` имеет тип `React.ReactNode`

2023-12-28 22:48 UTC, fogarea commented on src/ui/form/DateField/DateField.tsx
>          ...props.viewProps,
обычно стараются использовать `spread` оператор вверху объекта

2023-12-28 22:48 UTC, fogarea commented on src/ui/form/DateTimeField/DateTimeField.tsx
> +    const viewProps = useMemo(() => ({
добавить `import React`

2023-12-29 05:33 UTC, NicolaAK commented on src/ui/form/DateField/DateField.tsx
> +    const viewProps = useMemo(() => ({
done

2023-12-29 05:33 UTC, NicolaAK commented on src/ui/form/DateField/DateField.tsx
>          ...props.viewProps,
done

2023-12-29 05:34 UTC, NicolaAK commented on src/ui/form/DateTimeField/DateTimeField.tsx
> +    const viewProps = useMemo(() => ({
done

2023-12-29 06:38 UTC, fogarea approved these changes

2024-01-10 03:19 UTC, Daria-Kuzminykh commented on src/ui/form/DateRangeField/DateRangeField.tsx
> +        errors: props.errors,
По какой причине вместо errorsTo и errorsFrom стали errors? Если долго объяснять, то можно созвониться

2024-01-10 03:19 UTC, Daria-Kuzminykh commented on src/ui/form/DateRangeField/DateRangeField.tsx
> -        noBorder: props.noBorder,
Если этот проп не используется, то из defaultProps его тоже нужно убрать

2024-01-10 05:51 UTC, NicolaAK commented on src/ui/form/DateRangeField/DateRangeField.tsx
> +        errors: props.errors,
Во `view `их нет, там используется только `errors`

2024-01-10 06:18 UTC, NicolaAK commented on src/ui/form/DateRangeField/DateRangeField.tsx
> +        errors: props.errors,
Костя объяснил, поправил
Done

2024-01-10 06:18 UTC, NicolaAK commented on src/ui/form/DateRangeField/DateRangeField.tsx
> -        noBorder: props.noBorder,
Done

2024-01-11 03:06 UTC, Daria-Kuzminykh commented on src/ui/form/DateTimeRangeField/DateTimeRangeField.tsx
> -        errorsFrom: props.errorsFrom,
А в этом месте тоже тогда нужно оставить errorsFrom

2024-01-11 03:06 UTC, Daria-Kuzminykh commented on src/ui/form/DateTimeRangeField/DateTimeRangeField.tsx
> -        errorsFrom: props.errorsFrom,
А добавленные errors убрать

2024-01-11 03:08 UTC, Daria-Kuzminykh commented on src/ui/form/DateTimeRangeField/DateTimeRangeField.tsx
> -        errorsFrom: props.errorsFrom,
Обрати внимание на то, что если в одном месте написана правка, а в другом месте есть такая же ошибка, то нужно поправить во всех местах.

2024-01-11 06:09 UTC, NicolaAK commented on src/ui/form/DateTimeRangeField/DateTimeRangeField.tsx
> -        errorsFrom: props.errorsFrom,
не заметил сразу..
done

2024-01-11 10:01 UTC, merged