Steroids/dev#140 form 2 Передавать из core во view компонентов только необходимые пропсы
steroids/react pull request #306
Opened 2023-12-27 11:39 UTC by NicolaAK

2023-12-28 22:49 UTC, fogarea requested changes

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/EmailField/EmailField.tsx
>  /* eslint-disable max-len */
если переносишь массив зависимостей на новую строку, то это можно удалить

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/Form/Form.tsx
> +        isSubmitting,
нужно вернуть `...props.viewProps`, тк это проп для передачи свойств при переопределении `view`

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/NumberField/NumberField.ts
> +    const viewProps = useMemo(() => ({
интерфейс `INumberFieldProps` расширяется `IBaseFieldProps`, который имеет внутри проп `viewProps`. Его тоже нужно передавать во `view`

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/PasswordField/PasswordField.ts
> +    const viewProps = useMemo(() => ({
расширяется `IBaseFieldProps` как выше

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/RadioField/RadioField.tsx
> +import {checkPassword} from '@steroidsjs/core/ui/form/PasswordField/PasswordField';
не используется

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/SwitcherField/SwitcherField.tsx
>  import * as React from 'react';
тут предлагаю сделать `import React from 'react';`, а то получается две строчки для импорта сначала всего из `React`, а потом отдельно хуки

было бы хорошо исправить это и в других файлах

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/TextField/TextField.ts
> +    const viewProps = useMemo(() => ({
расширяется `IBaseFieldProps`

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/TimeField/TimeField.tsx
> +    const viewProps = useMemo(() => ({
вернуть `...props.viewProps`

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/TimeRangeField/TimeRangeField.tsx
> +    }), [extendedInputPropsFrom, extendedInputPropsTo, focus, isOpenedFrom, isOpenedTo, onClear, onClose, props.className,
добавить в массив зависимостей `props.errors`

2023-12-28 22:49 UTC, fogarea commented on src/ui/form/TimeRangeField/TimeRangeField.tsx
> +    const viewProps = useMemo(() => ({
вернуть `...props.viewProps`

2024-01-09 04:41 UTC, NicolaAK commented on src/ui/form/EmailField/EmailField.tsx
>  /* eslint-disable max-len */
done

2024-01-09 04:41 UTC, NicolaAK commented on src/ui/form/Form/Form.tsx
> +        isSubmitting,
done

2024-01-09 04:44 UTC, NicolaAK commented on src/ui/form/NumberField/NumberField.ts
> +    const viewProps = useMemo(() => ({
done

2024-01-09 04:44 UTC, NicolaAK commented on src/ui/form/PasswordField/PasswordField.ts
> +    const viewProps = useMemo(() => ({
done

2024-01-09 04:45 UTC, NicolaAK commented on src/ui/form/RadioField/RadioField.tsx
> +import {checkPassword} from '@steroidsjs/core/ui/form/PasswordField/PasswordField';
done

2024-01-09 04:47 UTC, NicolaAK commented on src/ui/form/SwitcherField/SwitcherField.tsx
>  import * as React from 'react';
done

2024-01-09 04:50 UTC, NicolaAK commented on src/ui/form/TextField/TextField.ts
> +    const viewProps = useMemo(() => ({
done

2024-01-09 04:52 UTC, NicolaAK commented on src/ui/form/TimeField/TimeField.tsx
> +    const viewProps = useMemo(() => ({
done

2024-01-09 04:52 UTC, NicolaAK commented on src/ui/form/TimeRangeField/TimeRangeField.tsx
> +    }), [extendedInputPropsFrom, extendedInputPropsTo, focus, isOpenedFrom, isOpenedTo, onClear, onClose, props.className,
done

2024-01-09 04:53 UTC, NicolaAK commented on src/ui/form/TimeRangeField/TimeRangeField.tsx
> +    const viewProps = useMemo(() => ({
done

2024-01-09 08:16 UTC, fogarea commented on src/ui/form/NumberField/NumberField.ts
> +    const viewProps = useMemo(() => ({
Изначально была структура 
```tsx
{
    props.inputProps,
    props.viewProps,
    ...
}
```

а теперь получается 
```tsx
{
    inputProps: {
        ...props.viewProps,
   },
   ...
}
```

`props.viewProps` должны передаваться во `view` на верхнем уровне вложености `viewProps`

2024-01-09 08:16 UTC, fogarea commented on src/ui/form/PasswordField/PasswordField.ts
> +    const viewProps = useMemo(() => ({
`props.viewProps` должны передаваться во `view` на верхнем уровне вложености `viewProps`

2024-01-10 06:40 UTC, NicolaAK commented on src/ui/form/PasswordField/PasswordField.ts
> +    const viewProps = useMemo(() => ({
done

2024-01-10 06:40 UTC, NicolaAK commented on src/ui/form/NumberField/NumberField.ts
> +    const viewProps = useMemo(() => ({
done

2024-01-10 06:50 UTC, fogarea approved these changes

2024-01-11 10:05 UTC, merged