Steroids/dev#588 form 3 Передавать из core во view компонентов только необходимые пропсы
steroids/react pull request #307
Opened 2023-12-28 11:10 UTC by NicolaAK

2023-12-28 23:11 UTC, fogarea requested changes

2023-12-28 23:11 UTC, fogarea commented on src/ui/form/NavField/NavField.tsx
> +        <Nav {...viewProps} />
Компонент `NavField` просто обертка над компонентом `Nav`.
Здесь можно оставить как было, или переименовать `viewProps`, потому что компонент `Nav` вызывается из `core` части

2023-12-28 23:16 UTC, fogarea commented
Добавь в этой ветке `viewProps` для `BlankField`, `MaskField`, `SliderField` (там где это нужно)

2023-12-29 05:41 UTC, NicolaAK commented on src/ui/form/FieldList/FieldList.tsx
> +        ...commonProps,
done

2023-12-29 05:47 UTC, NicolaAK commented on src/ui/form/NavField/NavField.tsx
>  import * as React from 'react';
done

2023-12-29 05:47 UTC, NicolaAK commented on src/ui/form/NavField/NavField.tsx
> +        <Nav {...viewProps} />
done

2024-01-09 08:29 UTC, fogarea approved these changes

2024-01-10 01:38 UTC, Daria-Kuzminykh commented on src/ui/form/InputField/InputField.tsx
> +        ...props,
Эта строчка сводит на нет всю выше проделанную работу. Мы избавляемся от конструкций ...props

2024-01-10 01:38 UTC, Daria-Kuzminykh commented on src/ui/form/MaskField/MaskField.tsx
> +        mask,
В прошлой версии файла как будто не использовались пропсы на строчках 17-18. Вообще, судя по коду использования, MaskField - это просто другое название компонента, никакая логика не добавляется. Весь компонент может быть строчкой - <InputField {...props} />

Проверь, что так будет работать и если все ок, то замени. (Удалить не можем этот компонент, потому что он указан в гранте)

2024-01-10 05:10 UTC, NicolaAK commented on src/ui/form/MaskField/MaskField.tsx
> +        mask,
done

2024-01-10 05:31 UTC, NicolaAK commented on src/ui/form/MaskField/MaskField.tsx
> +        mask,
done

2024-01-10 06:28 UTC, NicolaAK commented on src/ui/form/InputField/InputField.tsx
> +        ...props,
done

2024-01-10 06:40 UTC, NicolaAK commented on src/ui/form/InputField/InputField.tsx
> +        ...props,
done

2024-01-11 10:06 UTC, merged